config/routes.rb
Newcar::Application.routes.draw do
  resources :tturnos

  resources :turnos do
    collection do
      post 'saveallturnos'
      post 'saveturno'
    end
  end
  
  resources :ofcars

  resources :movils do
    collection do
      get 'addmovil'
    end
  end

  resources :tvehiculos

  resources :vehiculos do
    collection do
      get 'addvehiculo'
      get 'getvehicdisp'
    end
  end

  resources :contratistas

  resources :personals do
    collection do
      get 'addpersonal'
      get 'getpersdisp'
    end
  end

  resources :usuarios do
    collection do
      get 'find'
      get 'actpwd'
    end
  end

  resources :cuentas do
    collection do
      get 'addcuenta'
    end
  end

  resources :actividads do
    collection do
      get 'addactividad'
      get 'indexcuentasactividadmes'
      get 'indexcuentasactividaddia'
    end
  end

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
	belongs_to :cuenta
end

app/models/contratista.rb
class Contratista < ActiveRecord::Base
	has_many :personals
end

app/models/cuenta.rb
class Cuenta < ActiveRecord::Base
	has_ancestry
	has_many :actividads
end

app/models/movil.rb
class Movil < ActiveRecord::Base
	has_many :personals
	has_one  :vehiculo
	belongs_to :ofcar
	has_many :turnos
end

app/models/ofcar.rb
class Ofcar < ActiveRecord::Base
	has_many :movils
	has_many :turnos
end

app/models/personal.rb
class Personal < ActiveRecord::Base
	belongs_to :contratista
	belongs_to :movil
	
end

app/models/tturno.rb
class Tturno < ActiveRecord::Base
	has_many :turnos
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :movil
	belongs_to :ofcar
	belongs_to :tturno
end

app/models/tvehiculo.rb
class Tvehiculo < ActiveRecord::Base
	has_many :vehiculos
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
	belongs_to :tvehiculo
	belongs_to :movil
end

app/controllers/tvehiculos_controller.rb
class TvehiculosController < ApplicationController
  # GET /tvehiculos
  # GET /tvehiculos.xml
  def index
    @tvehiculos = Tvehiculo.all

    cadena = gettvehiculos(@tvehiculos)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => cadena }
    end
  end

  def gettvehiculos(tvehiculos)

    cadena = ''
    x = Builder::XmlMarkup.new(:target => cadena, :indent => 1)
    x.instruct!

    x.tvehiculos {
      tvehiculos.each {|t|
        x.tvehiculo(:id=>t.id,:tipo=>t.tipo)
      }
    }
    return cadena
  end

  # GET /tvehiculos/1
  # GET /tvehiculos/1.xml
  def show
    @tvehiculo = Tvehiculo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tvehiculo }
    end
  end

  # GET /tvehiculos/new
  # GET /tvehiculos/new.xml
  def new
    @tvehiculo = Tvehiculo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tvehiculo }
    end
  end

  # GET /tvehiculos/1/edit
  def edit
    @tvehiculo = Tvehiculo.find(params[:id])
  end

  # POST /tvehiculos
  # POST /tvehiculos.xml
  def create
    @tvehiculo = Tvehiculo.new(params[:tvehiculo])

    respond_to do |format|
      if @tvehiculo.save
        format.html { redirect_to(@tvehiculo, :notice => 'Tvehiculo was successfully created.') }
        format.xml  { render :xml => @tvehiculo, :status => :created, :location => @tvehiculo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tvehiculo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tvehiculos/1
  # PUT /tvehiculos/1.xml
  def update
    @tvehiculo = Tvehiculo.find(params[:id])

    respond_to do |format|
      if @tvehiculo.update_attributes(params[:tvehiculo])
        format.html { redirect_to(@tvehiculo, :notice => 'Tvehiculo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tvehiculo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tvehiculos/1
  # DELETE /tvehiculos/1.xml
  def destroy
    @tvehiculo = Tvehiculo.find(params[:id])
    @tvehiculo.destroy

    respond_to do |format|
      format.html { redirect_to(tvehiculos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuentas_helper.rb
module CuentasHelper
end

app/helpers/movils_helper.rb
module MovilsHelper
end

app/helpers/ofcars_helper.rb
module OfcarsHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/tturnos_helper.rb
module TturnosHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/tvehiculos_helper.rb
module TvehiculosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/tvehiculos/_form.html.erb
<%= form_for(@tvehiculo) do |f| %>
  <% if @tvehiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tvehiculo.errors.count, "error") %> prohibited this tvehiculo from being saved:</h2>

      <ul>
      <% @tvehiculo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tvehiculos/edit.html.erb
<h1>Editing tvehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tvehiculo %> |
<%= link_to 'Back', tvehiculos_path %>

app/views/tvehiculos/index.html.erb
<h1>Listing tvehiculos</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tvehiculos.each do |tvehiculo| %>
  <tr>
    <td><%= tvehiculo.tipo %></td>
    <td><%= link_to 'Show', tvehiculo %></td>
    <td><%= link_to 'Edit', edit_tvehiculo_path(tvehiculo) %></td>
    <td><%= link_to 'Destroy', tvehiculo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tvehiculo', new_tvehiculo_path %>

app/views/tvehiculos/new.html.erb
<h1>New tvehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', tvehiculos_path %>

app/views/tvehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @tvehiculo.tipo %>
</p>


<%= link_to 'Edit', edit_tvehiculo_path(@tvehiculo) %> |
<%= link_to 'Back', tvehiculos_path %>