config/routes.rb
Newcar::Application.routes.draw do
  resources :tturnos

  resources :turnos do
    collection do
      post 'saveallturnos'
      post 'saveturno'
    end
  end
  
  resources :ofcars

  resources :movils do
    collection do
      get 'addmovil'
    end
  end

  resources :tvehiculos

  resources :vehiculos do
    collection do
      get 'addvehiculo'
      get 'getvehicdisp'
    end
  end

  resources :contratistas

  resources :personals do
    collection do
      get 'addpersonal'
      get 'getpersdisp'
    end
  end

  resources :usuarios do
    collection do
      get 'find'
      get 'actpwd'
    end
  end

  resources :cuentas do
    collection do
      get 'addcuenta'
    end
  end

  resources :actividads do
    collection do
      get 'addactividad'
      get 'indexcuentasactividadmes'
      get 'indexcuentasactividaddia'
    end
  end

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
	belongs_to :cuenta
end

app/models/contratista.rb
class Contratista < ActiveRecord::Base
	has_many :personals
end

app/models/cuenta.rb
class Cuenta < ActiveRecord::Base
	has_ancestry
	has_many :actividads
end

app/models/movil.rb
class Movil < ActiveRecord::Base
	has_many :personals
	has_one  :vehiculo
	belongs_to :ofcar
	has_many :turnos
end

app/models/ofcar.rb
class Ofcar < ActiveRecord::Base
	has_many :movils
	has_many :turnos
end

app/models/personal.rb
class Personal < ActiveRecord::Base
	belongs_to :contratista
	belongs_to :movil
	
end

app/models/tturno.rb
class Tturno < ActiveRecord::Base
	has_many :turnos
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :movil
	belongs_to :ofcar
	belongs_to :tturno
end

app/models/tvehiculo.rb
class Tvehiculo < ActiveRecord::Base
	has_many :vehiculos
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
	belongs_to :tvehiculo
	belongs_to :movil
end

app/controllers/ofcars_controller.rb
class OfcarsController < ApplicationController
  # GET /ofcars
  # GET /ofcars.xml
  def index
    @ofcars = Ofcar.all

    cadena = getofcars(@ofcars)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => cadena }
    end
  end

  def getofcars(ofcars)

    cadena = ''
    x = Builder::XmlMarkup.new(:target => cadena, :indent => 1)
    x.instruct!

    x.ofcars {
      ofcars.each {|o|
        x.ofcar(:id=>o.id,:oficina=>o.oficina)
      }
    }
    return cadena
  end

  # GET /ofcars/1
  # GET /ofcars/1.xml
  def show
    @ofcar = Ofcar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ofcar }
    end
  end

  # GET /ofcars/new
  # GET /ofcars/new.xml
  def new
    @ofcar = Ofcar.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ofcar }
    end
  end

  # GET /ofcars/1/edit
  def edit
    @ofcar = Ofcar.find(params[:id])
  end

  # POST /ofcars
  # POST /ofcars.xml
  def create
    @ofcar = Ofcar.new(params[:ofcar])

    respond_to do |format|
      if @ofcar.save
        format.html { redirect_to(@ofcar, :notice => 'Ofcar was successfully created.') }
        format.xml  { render :xml => @ofcar, :status => :created, :location => @ofcar }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ofcar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ofcars/1
  # PUT /ofcars/1.xml
  def update
    @ofcar = Ofcar.find(params[:id])

    respond_to do |format|
      if @ofcar.update_attributes(params[:ofcar])
        format.html { redirect_to(@ofcar, :notice => 'Ofcar was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ofcar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ofcars/1
  # DELETE /ofcars/1.xml
  def destroy
    @ofcar = Ofcar.find(params[:id])
    @ofcar.destroy

    respond_to do |format|
      format.html { redirect_to(ofcars_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuentas_helper.rb
module CuentasHelper
end

app/helpers/movils_helper.rb
module MovilsHelper
end

app/helpers/ofcars_helper.rb
module OfcarsHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/tturnos_helper.rb
module TturnosHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/tvehiculos_helper.rb
module TvehiculosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/ofcars/_form.html.erb
<%= form_for(@ofcar) do |f| %>
  <% if @ofcar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ofcar.errors.count, "error") %> prohibited this ofcar from being saved:</h2>

      <ul>
      <% @ofcar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :oficina %><br />
    <%= f.text_field :oficina %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ofcars/edit.html.erb
<h1>Editing ofcar</h1>

<%= render 'form' %>

<%= link_to 'Show', @ofcar %> |
<%= link_to 'Back', ofcars_path %>

app/views/ofcars/index.html.erb
<h1>Listing ofcars</h1>

<table>
  <tr>
    <th>Oficina</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ofcars.each do |ofcar| %>
  <tr>
    <td><%= ofcar.oficina %></td>
    <td><%= link_to 'Show', ofcar %></td>
    <td><%= link_to 'Edit', edit_ofcar_path(ofcar) %></td>
    <td><%= link_to 'Destroy', ofcar, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ofcar', new_ofcar_path %>

app/views/ofcars/new.html.erb
<h1>New ofcar</h1>

<%= render 'form' %>

<%= link_to 'Back', ofcars_path %>

app/views/ofcars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Oficina:</b>
  <%= @ofcar.oficina %>
</p>


<%= link_to 'Edit', edit_ofcar_path(@ofcar) %> |
<%= link_to 'Back', ofcars_path %>