config/routes.rb
Newcar::Application.routes.draw do
  resources :tturnos

  resources :turnos do
    collection do
      post 'saveallturnos'
      post 'saveturno'
    end
  end
  
  resources :ofcars

  resources :movils do
    collection do
      get 'addmovil'
    end
  end

  resources :tvehiculos

  resources :vehiculos do
    collection do
      get 'addvehiculo'
      get 'getvehicdisp'
    end
  end

  resources :contratistas

  resources :personals do
    collection do
      get 'addpersonal'
      get 'getpersdisp'
    end
  end

  resources :usuarios do
    collection do
      get 'find'
      get 'actpwd'
    end
  end

  resources :cuentas do
    collection do
      get 'addcuenta'
    end
  end

  resources :actividads do
    collection do
      get 'addactividad'
      get 'indexcuentasactividadmes'
      get 'indexcuentasactividaddia'
    end
  end

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
	belongs_to :cuenta
end

app/models/contratista.rb
class Contratista < ActiveRecord::Base
	has_many :personals
end

app/models/cuenta.rb
class Cuenta < ActiveRecord::Base
	has_ancestry
	has_many :actividads
end

app/models/movil.rb
class Movil < ActiveRecord::Base
	has_many :personals
	has_one  :vehiculo
	belongs_to :ofcar
	has_many :turnos
end

app/models/ofcar.rb
class Ofcar < ActiveRecord::Base
	has_many :movils
	has_many :turnos
end

app/models/personal.rb
class Personal < ActiveRecord::Base
	belongs_to :contratista
	belongs_to :movil
	
end

app/models/tturno.rb
class Tturno < ActiveRecord::Base
	has_many :turnos
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	belongs_to :movil
	belongs_to :ofcar
	belongs_to :tturno
end

app/models/tvehiculo.rb
class Tvehiculo < ActiveRecord::Base
	has_many :vehiculos
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
	belongs_to :tvehiculo
	belongs_to :movil
end

app/controllers/tturnos_controller.rb
class TturnosController < ApplicationController
  # GET /tturnos
  # GET /tturnos.xml
  def index
    @tturnos = Tturno.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tturnos }
    end
  end

  # GET /tturnos/1
  # GET /tturnos/1.xml
  def show
    @tturno = Tturno.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tturno }
    end
  end

  # GET /tturnos/new
  # GET /tturnos/new.xml
  def new
    @tturno = Tturno.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tturno }
    end
  end

  # GET /tturnos/1/edit
  def edit
    @tturno = Tturno.find(params[:id])
  end

  # POST /tturnos
  # POST /tturnos.xml
  def create
    @tturno = Tturno.new(params[:tturno])

    respond_to do |format|
      if @tturno.save
        format.html { redirect_to(@tturno, :notice => 'Tturno was successfully created.') }
        format.xml  { render :xml => @tturno, :status => :created, :location => @tturno }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tturno.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tturnos/1
  # PUT /tturnos/1.xml
  def update
    @tturno = Tturno.find(params[:id])

    respond_to do |format|
      if @tturno.update_attributes(params[:tturno])
        format.html { redirect_to(@tturno, :notice => 'Tturno was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tturno.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tturnos/1
  # DELETE /tturnos/1.xml
  def destroy
    @tturno = Tturno.find(params[:id])
    @tturno.destroy

    respond_to do |format|
      format.html { redirect_to(tturnos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuentas_helper.rb
module CuentasHelper
end

app/helpers/movils_helper.rb
module MovilsHelper
end

app/helpers/ofcars_helper.rb
module OfcarsHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/tturnos_helper.rb
module TturnosHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/tvehiculos_helper.rb
module TvehiculosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/tturnos/_form.html.erb
<%= form_for(@tturno) do |f| %>
  <% if @tturno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tturno.errors.count, "error") %> prohibited this tturno from being saved:</h2>

      <ul>
      <% @tturno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :turno %><br />
    <%= f.text_field :turno %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tturnos/edit.html.erb
<h1>Editing tturno</h1>

<%= render 'form' %>

<%= link_to 'Show', @tturno %> |
<%= link_to 'Back', tturnos_path %>

app/views/tturnos/index.html.erb
<h1>Listing tturnos</h1>

<table>
  <tr>
    <th>Turno</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tturnos.each do |tturno| %>
  <tr>
    <td><%= tturno.turno %></td>
    <td><%= tturno.desc %></td>
    <td><%= link_to 'Show', tturno %></td>
    <td><%= link_to 'Edit', edit_tturno_path(tturno) %></td>
    <td><%= link_to 'Destroy', tturno, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tturno', new_tturno_path %>

app/views/tturnos/new.html.erb
<h1>New tturno</h1>

<%= render 'form' %>

<%= link_to 'Back', tturnos_path %>

app/views/tturnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Turno:</b>
  <%= @tturno.turno %>
</p>

<p>
  <b>Desc:</b>
  <%= @tturno.desc %>
</p>


<%= link_to 'Edit', edit_tturno_path(@tturno) %> |
<%= link_to 'Back', tturnos_path %>